services:
  - type: web
    name: song-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run songrec.py
    pythonVersion: 3.10.13
    branch: master
    plan: free
